cmake_minimum_required(VERSION 3.13)
include_guard(GLOBAL)
option(DOCTEST_WITH_TESTS OFF)
option(DOCTEST_WITH_MAIN_IN_STATIC_LIB OFF)
option(DOCTEST_NO_INSTALL ON)
set(
    DOCTEST_COMPILE_DEFINITIONS
    DOCTEST_CONFIG_NO_EXCEPTIONS 
    DOCTEST_CONFIG_ASSERTION_PARAMETERS_BY_VALUE 
    DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING
    USING_DOCTEST
    CACHE INTERNAL ""
)
add_subdirectory(
    ${CMAKE_CURRENT_LIST_DIR}
    "external/doctest"
)
